### PR TITLE
fix(test): forward passwordRef/confirmPasswordRef in RegisterForm real-flow test mock

### PR DESCRIPTION
**Pull request by stevenayal**
## Summary

- `RegisterForm.tsx` reads `password`/`confirmPassword` at submit time via `passwordRef.current?.value` / `confirmPasswordRef.current?.value` — these are refs forwarded down to `AuthForm`, which attaches them (`ref={passwordRef}`, `ref={confirmPasswordRef}`) to its uncontrolled password inputs.
- The `AuthForm` mock in `test/components/auth/RegisterForm.real.test.tsx` never accepted or attached those refs, so `passwordRef.current` was always `null` at submit time regardless of what the test typed — `validateForm()` always saw `password: '', confirmPassword: ''`, produced "Contraseña obligatoria"/"Confirmar contraseña obligatorio" errors, and `handleSubmit` short-circuited (`if (!validateForm()) return;`) before ever calling the registration action.
- This is one of the 14 pre-existing failures tracked in #314 ("Required check 'Lint & Unit Tests' is permanently red on main"). Fixes 2 of the 3 previously-failing tests in this file (verified locally: `pnpm --filter @aiquaa/frontend test -- RegisterForm.real` goes from 1 passed/3 failed to 3 passed/1 failed).

## Remaining failure in this file (not fixed here, out of scope)

The 4th test ("muestra éxito y programa la redirección al login tras registrarse") still fails for an unrelated, deeper reason: this test file mocks a `useNextAuth().register()` call, but `RegisterForm.tsx` no longer uses that hook — it now calls the `registerAction` server action directly (imported from `@/actions/auth`). Since `registerAction` isn't mocked in this file, the real server action executes in the test environment. Fixing this properly means mocking `registerAction` (like `RegisterForm.test.tsx` already does) and rewriting the assertions around it, which is a larger change than this scoped ref-forwarding fix and risks masking other behavior — left as a follow-up.

## Verification

- `pnpm --filter @aiquaa/frontend test -- RegisterForm.real` — 3/4 passing (was 1/4).
- Full `pnpm --filter @aiquaa/frontend test` — 32 failing (was 33 on `main`, per #314), no new failures introduced; same 15 pre-existing failing files as documented in #314.
- `pnpm exec eslint` on the changed file — clean.
- `pnpm --filter @aiquaa/frontend type-check` — clean.

## Context

Found and fixed during an automated, unattended QA-cycle session (no live human watching) while investigating the pre-existing test failures tracked in #314, which itself blocks the required CI check for #309 (SEC-HIGH, exam answer key exposed client-side) and other pending PRs.

---
_Generated by [Claude Code](https://claude.ai/code/session_019LR8tZwguN8hRiKHzThGD1)_

### CODE REVIEW

**Comment by stevenayal** [comment]
The `Lint & Unit Tests` required check is red here, but it's not caused by this PR's diff — the failure is `TypeError: window.matchMedia is not a function` at `src/components/LogoMark.tsx:77`, which reproduces identically on a clean checkout of `main` (verified locally before opening this PR: `main` has 33 pre-existing failures, this branch has 32, no new failures). It's the same root cause tracked in #314 and already fixed (unmerged) by PR #312.

Not widening this PR's scope to fix it — that's PR #312's job. This PR only touches `RegisterForm.real.test.tsx` to fix the `passwordRef`/`confirmPasswordRef` forwarding bug described above, verified locally with `pnpm --filter @aiquaa/frontend test -- RegisterForm.real` (1/4 → 3/4 passing) and against the full suite (no regressions).


---
_Generated by [Claude Code](https://claude.ai/code)_
