### PR TITLE
fix(frontend): polyfill window.matchMedia in test setup

### PR DESCRIPTION
**Pull request by stevenayal**
## Summary

- `jsdom` (the test DOM used by Vitest) does not implement `window.matchMedia`. `LogoMark.tsx` calls it directly in a `useEffect` to respect `prefers-reduced-motion`, and `LogoMark` is rendered by `Header`/`Footer`/`AuthForm`, so any test that mounts those components throws `TypeError: window.matchMedia is not a function`.
- This is the exact failure documented in PR #309's "Lint & Unit Tests" required check (`window.matchMedia is not a function in LogoMark.tsx:77`), which has been blocking merge of the #225 (SEC-HIGH) fix for 2 days, and was previously flagged as a pre-existing, unrelated failure in QA-cycle issues #310/#311.
- Adds a minimal `matchMedia` polyfill to `apps/frontend/test/setup.ts` (standard jsdom mock shape: `matches`, `media`, `addEventListener`/`removeEventListener`, etc., defaulting `matches: false`).

## Verification

- Before: this class of failure occurred wherever `LogoMark` was mounted (Header/Footer/AuthForm-adjacent tests).
- After: `grep -c matchMedia` on a full `pnpm --filter @aiquaa/frontend test` run returns `0` — no more matchMedia-related failures anywhere in the suite.
- Full suite went from the previously-reported 33 pre-existing failures to 14 (all unrelated — separate pre-existing mock/timing issues in `RegisterForm`/`LoginForm` real-flow tests, e.g. `checkEmailTakenAction` not exported from a `vi.mock`). Those are a separate, deeper issue and out of scope here.
- `pnpm --filter @aiquaa/frontend type-check` and `eslint --fix` (via lint-staged pre-commit hook) pass clean on the changed file.
- Change is additive-only (one new polyfill block), touches no other logic, so it carries no regression risk to passing tests.

## Context

Found and fixed during an automated, unattended QA-cycle session (no live human watching) while investigating why PR #309 has sat with a red required check for 2 days despite the check being unrelated to its diff. Fixing the shared test-infra issue is lower-risk and higher-leverage than special-casing it in #309.

---
_Generated by [Claude Code](https://claude.ai/code/session_013e1A5yUtBqp8oxW71tJ3WC)_

### CODE REVIEW

**Comment by stevenayal** [comment]
## CI status: `Lint & Unit Tests` will stay red — explained, tracked separately

The required check just failed here too, for the same reason it's been failing on #309: it requires **zero** test failures, and `main` currently has **33 pre-existing, unrelated failures across 15 files** (verified locally against a clean `origin/main` checkout, no diff applied).

This PR's fix is doing exactly what it claims: it eliminates every `window.matchMedia`-caused failure (confirmed via `grep -c matchMedia` on the full run: `0` after the fix, vs. crashes in every `Header`/`Footer`/`AuthForm`-adjacent test before it) and takes the suite from 33 failing tests down to **14**. It does not, and was never going to, take it to zero — the remaining 14 are a separate, pre-existing problem (broken `checkEmailTakenAction` mock in `RegisterForm`/`LoginForm` real-flow tests, plus several files failing to even collect) unrelated to this diff or to #225.

Filed **#314** to track that remaining work — it's a real fix but not a small one, and out of scope here. Not attempting it in this PR.

Net effect if merged: the required check goes from "33 failures, includes matchMedia crashes affecting broadly-used components" to "14 failures, all tracked in #314" — smaller blast radius, but the check itself will still show red on this PR and on #309 until #314 is resolved (or the check is temporarily relaxed — see proposal in #314).


---
_Generated by [Claude Code](https://claude.ai/code)_
